apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster-lb
  namespace: elastic-system
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.0.230  # Replace with your kube-vip IP
spec:
  type: LoadBalancer
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-cluster
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200

