apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: elastic-system
  annotations:
    # Annotations can be used for ECK-specific configurations or integrations
    elasticsearch.k8s.elastic.co/initial-master-nodes: elasticsearch-cluster-es-master-nodes-0
spec:
  version: 8.16.1  # Specify the Elasticsearch version
  nodeSets:
  - name: master-nodes
    count: 1  # Number of nodes in this node set
    podTemplate:
      spec:
        securityContext:
          fsGroup: 1000       # Filesystem group for the Elasticsearch data directory
          runAsUser: 1000     # Elasticsearch runs as user ID 1000 (non-root)
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi      # Request 2Gi of memory
              cpu: 1           # Request 1 CPU core
            limits:
              memory: 2Gi      # Limit memory usage to 2Gi
              cpu: 2           # Limit CPU usage to 2 CPU cores
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"  # Set JVM heap size
        initContainers:
        - name: sysctl
          command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
          securityContext:
            privileged: true
            runAsUser: 0
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: manual  # Replace with your storage class
        resources:
          requests:
            storage: 10Gi  # Specify the storage size for the data volume
    config:
      cluster.initial_master_nodes:  # Specify the initial master node(s) for multi-node clusters
        - elasticsearch-cluster-es-master-nodes-0
      network.host: 0.0.0.0  # Allow Elasticsearch to bind to all network interfaces
      node.name: elasticsearch-cluster-es-master-nodes-0  # Ensure node naming consistency

