apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: elastic-system
spec:
  version: 8.16.1
  nodeSets:
  - name: master-nodes
    count: 1
    podTemplate:
      spec:
        securityContext:
          fsGroup: 1000       # Filesystem group for the Elasticsearch data directory
          runAsUser: 1000     # Elasticsearch runs as user ID 1000 (non-root)
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi      # Request 2Gi of memory
              cpu: 1           # Request 1 CPU core
            limits:
              memory: 2Gi      # Limit memory usage to 2Gi
              cpu: 2           # Limit CPU usage to 2 CPU cores
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"  # Set JVM heap size
        initContainers:
        - name: sysctl
          command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
          securityContext:
            privileged: true
            runAsUser: 0
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: manual  # Replace with your storage class
        resources:
          requests:
            storage: 10Gi
    config:
      discovery.type: single-node    # Use single-node for now
      # cluster.initial_master_nodes:
      #   - elasticsearch-cluster-es-master-nodes-0 # Uncomment when moving to a multi-node cluster

