apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster-lb
  namespace: elastic-system
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.0.230
spec:
  type: LoadBalancer
  selector:
    common.k8s.elastic.co/type: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
