apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  http:
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.230 # Assign the shared kube-vip IP for Kibana
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.publicBaseUrl: "http://192.168.0.230:5601" # Update to match LoadBalancer IP and Kibana's port
    #server.publicBaseUrl: "https://baba.local:5601"
    #server.basePath: "/kibana"                       # Optional, remove if unnecessary
    #server.rewriteBasePath: true                     # Optional, based on basePath usage
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1024"

