apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: elastic-system
spec:
  version: 8.16.1
  nodeSets:
  - name: master-nodes
    count: 1
    config:
      # Add recommended Elasticsearch settings
      node.store.allow_mmap: false
      indices.memory.index_buffer_size: "10%"
      indices.queries.cache.size: "5%"
      thread_pool.write.queue_size: 1000
    podTemplate:
      spec:
        # Add affinity rules for better pod scheduling
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-cluster
                topologyKey: kubernetes.io/hostname
        # Add health probes
        containers:
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /usr/share/elasticsearch/bin/elasticsearch-plugin list
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
        initContainers:
        - name: sysctl
          command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
          securityContext:
            privileged: true
            runAsUser: 0
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: manual  # Replace with your storage class
        resources:
          requests:
            storage: 10Gi
    #config:
    #  xpack.security.enabled: false   # Disable security (including HTTPS and authentication)
    #  http.port: 9200                 # Ensure the HTTP port is set
    #  node.store.allow_mmap: false

