apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.publicBaseUrl: "http://baba.local/kibana"
    server.basePath: "/kibana"
    server.rewriteBasePath: true

  #config:
  #  elasticsearch.hosts: ["https://elasticsearch-cluster-es-http:9200"]
  #  elasticsearch.ssl.verificationMode: "none"  # Disable certificate validation for testing

  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          # Define CPU and memory requests and limits for Kibana
          # Recommendation: Monitor resource usage and adjust based on workload.
          requests:
            memory: 1Gi          # Request 1Gi of memory
            cpu: 500m            # Request 0.5 CPU core
          limits:
            memory: 2Gi          # Limit memory usage to 2Gi
            cpu: 1               # Limit CPU usage to 1 CPU core
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1024"  # Set max heap size for Kibana to 1Gi
