apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  config:
    server.publicBaseUrl: "http://baba.local/kibana"
    server.basePath: "/kibana"
    server.rewriteBasePath: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
