apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.publicBaseUrl: "http://baba.local/kibana"
    server.basePath: "/kibana"
    server.rewriteBasePath: true

  #config:
  #  elasticsearch.hosts: ["https://elasticsearch-cluster-es-http:9200"]
  #  elasticsearch.ssl.verificationMode: "none"  # Disable certificate validation for testing

