apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-data-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/elasticsearch-data-1

